function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "reset")
	self.runningAnimation = false
end

function explodeAnimate(self, runningAnimation)
	sprite.play_flipbook("#sprite", "explode", function()
		self.runningAnimation=false
		sprite.play_flipbook("#sprite", "lowBoule")
	end)
end

function updateScore(self)
	scorejoueurs[joueurEnCours]=scorejoueurs[joueurEnCours]+1
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	if cibleEnCours==4 then
		--print(self.runningAnimation)
		if self.runningAnimation == false then
			sprite.play_flipbook("#sprite", "TagetToHit")
			self.runningAnimation=true
		end
	end
	
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("TOUCHE") then
		print("receive message") 

		if cibleEnCours==4 then
			explodeAnimate(self, self.runningAnimation)
			updateScore()
			hitCount()
			reste = reste -1
			gererInterruptions()
		end


	end

	if message_id == hash("RATE") then
		print("receive message") 

		if cibleEnCours==4 then
			missCount()
			reste = reste -1
			sprite.play_flipbook("#sprite", "lowBoule")
			self.runningAnimation=false
			gererInterruptions()
		end


	end
end

function on_input(self, action_id, action)
	if action_id == hash("hit4") then --TEST 2
		--print(self.runningAnimation)
		if action.released then
			if cibleEnCours==4 then
				updateScore()
				hitCount()
				reste = reste -1
				gererInterruptions()
			end 
		end
		explodeAnimate(self, self.runningAnimation)
	end -- FIN TEST 3
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
